name: test

on:
  push:
    branches:
      - master

jobs:
  docker-compose:
    name: compose
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: docker pull
        run: docker pull kennethreitz/httpbin:latest

      - name: docker-compose
        run: docker-compose up -d

      - name: inspect
        run: |
          echo 'docker ps'
          docker ps
          echo ''
          echo 'ifconfig'
          ifconfig

      - name: run curl
        run: |
          curl -i --head http://localhost:3000/get

      - name: down
        run: docker-compose down
